CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    send_at TIMESTAMPTZ NOT NULL,
    repeat VARCHAR(255) NOT NULL,
    is_sent BOOLEAN NOT NULL DEFAULT FALSE,
    dt_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dt_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
